# Default values for skyvafnir-network-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
skyvafnir:
  prefixPath: /skyvafnir
ingress:
  enabled: true
#  className: "nginx"
  className: "azure-application-gateway"
  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: azure/application-gateway  # Azure AKS AGIC
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"    # Rewrite backend path to "/"
