# Default values for skyvafnir-network-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
skyvafnir:
  prefixPath: /skyvafnir
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
