apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "skyvafnir-network-test.fullname" . }}-urls
  labels:
    {{- include "skyvafnir-network-test.labels" . | nindent 4 }}
data:
  URLS: {{ join "," .Values.skyvafnir.networkTester.urls }}