apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  labels:
    {{- include "skyvafnir-network-test.labels" . | nindent 4 }}
    kubernetes.io/metadata.name: {{ include "skyvafnir-network-test.fullname" . }}
  namespace: {{ include "skyvafnir-network-test.fullname" . }} 
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Ingress
  - Egress
