apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "skyvafnir-network-test.fullname" . }}
  labels:
    {{- include "skyvafnir-network-test.labels" . | nindent 4 }}
  annotations:
    # AGIC
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "skyvafnir-network-test.fullname" . }}

            port:
              number: {{ .Values.service.port }}
