name: release

env:
  DOCKER_REPO: skyvafnir/skyvafnir-network-test
  VERSION: ${{ github.ref_name }}
on:
  push:
    tags:
    - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Version stamp
        run: echo ${{ env.VERSION }} > VERSION
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.DOCKER_REPO }}:${{ env.VERSION }}
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            "VERSION=${{ env.VERSION }}"
            "GIT_SHA=${{ github.sha }}"